### ISSUE TITLE
Everything Wrong With Alex's Code (that I found)

### ISSUE THREAD

**Issue by manolipt** [Team-Pronto-3070/2017_Master#39]
General    **TR: Low priority, won't cause errors.**  Manoli: Sure, but if one of the programmers is out there trying to find a logic error in the code it doesn't help if Alex is the only one who can understand it. Not all of this needs to be done, but it really should have its comments updated. Alex, if you have time Friday night after setup this would be EXTREMELY helpful and a lifesaver in many cases.
- Re-comment all classes (it'd be nice if I didn't have to do that this time)
- Improve readability
- Check imports to make sure we're using all of them
- Get rid of unnecessary comments and code
- Make sure we are only printing things we would need to see to the smartDash

Auto.java
- autoSkeleton() is unnecessary  **TR: Low priority, won't cause errors.** 
- autoOutside() and autoOutsideCenter() distances are wrong  **TR: What would be correct?** Manoli: Check the manual to be precise, I know that firstDist for all auto codes is 6.5 (tested), autoOutside and autoOutsideCenter (to be autoCenterOutside - see below) as far as I'm aware have not been tested however, this is HIGH PRIORITY at the field if they haven't but if they have that's fine. All of these should have a distance offset of 0.5 (tested) subtracted from them as well.
- autoOutsideCenter() should be autoCenterOutside() (reverse values)  **TR: I don't see autoCenterOutside** Manoli: Logically, while there is not practical use or case where we would need to go from the outside start position to the center gearloader, there is a good arguement for going from the center starting position to the outside gearloader (in case one team can shoot but needs to start on the hopper side). This can be easily done by taking the inverse of the turn angles used for autoOutsideCenter() and using those instead, and this will make our lives easier in competition as we will also be able to shoot if this scenario ever comes up.
- Drive and Gyro classes should not be re-initialized, but rather inputted into the constructor  **TR: I prefer to create the objects in the constructor, but it'll still work in the class variable declaration.**
- Nothing in constructor  **TR: Low priority, won't cause errors.** 
line 138 - Case statement should be at top of function (stylistic)  **TR: Low priority, won't cause errors.** 
line 99 - should be an else if statement **TR: HIGH PRIORITY YES, even worse turnStarted is never set to true. Bad logic**
line 106 - unnecessary, default for robotShoot is false  **TR: OK to reset, some other code might change it.** 
line 122 - unnecessary, shooter won't shoot unless you tell it to **TR: Low priority, won't cause errors.** 
line 26 - initHeading should be checked within each function since the offset will likely change, especially if we have a turn **TR: Not sure about that. I think all angles after start are based off of this value.** Manoli: You reset the gyro after you turn/before you turn again, so it's important to constantly update the offset so we don't go the wrong direction after a turn
line 96 - robotShoot default is false **TR: OK to reset, some other code might change it.** 
line 99 - turnStarted needs to be set to true in this statement, otherwise program will not continue  **TR: HIGH PRIORITY**
line 109-115 - delete this **TR: Low priority, won't cause errors.** 
All instances of drive.turn - the speed should be set to Pronstants.AUTO_TURN_SPEED **TR: HIGH PRIORITY - YES**
line 173 - Why is this here? **TR: HIGH PRIORITY ? won't this keep changing the initHeading every cycle?** Manoli: Yes it will, but I see what Alex was trying to do. If we have this in, it will solve the previous problem of not updating the offset every cycle, but it needs to only be run once. Either way, I think just updating the offset each cycle is a neater and more error-proof way to do this (just because we won't have any problems if the robot doesn't turn exactly firstTurn amount of degrees)
line 171 - take out !secondTurning (stylistic, we'll get past this step even if we don't remove it I think) **TR: not sure** Manoli: It is worth removing in case, but it's not incredibly high priority, unless you see a logic error with it
line 178 - you can just say "!drive.turn..." **TR: Low priority, won't cause errors.** 
line 186 - unnecessary, robot won't drive unless you tell it to **TR: isn't this the end and OK?** Manoli: This is another low priority one, it won't cause errors it just doesn't need to be here.

Drive.java
83 - speeds are on the wrong sides of the input **TR: Don't know, if wrong, won't it drive poorly?** Manoli: That's the point, it won't drive correctly and will only cause frustration
110-111 - maybe don't want to print here considering how many times in the code we call these values, plus is not good formatting **TR: you could put in a counter and only update every 10 cycles (0.2 second)** Manoli: Sure, sounds like a good idea
164 - robot will only drive if you tell it to **TR: won't it not drive if it's wrong? TEST IT!! HIGH PRIORITY** Manoli: not sure I understand why this is high priority, this was the same issue above; it's just stylistic and isn't necessary, but it shouldn't cause errors
- driveRobotStraight() and driveRobotStraightSpeed should be one function
183 - we figured out it works better to drive the robot if you don't subtract adjSpeed from one side but rather just add it to the other, as to not slow down the robot (this has been tested, by the way)
179 - initialize adjSpeed outside function (stylistic)

Pronstants.java
48-53 - Why is this here again? There is another place to set string values for the smartDash, you know

ProntoGyro.java
34 - Don't print to smartDash **TR: you could put in a counter and only update every 10 cycles (0.2 second)** Manoli: See above, but sounds good
55 - Normalize heading value fixes this case already  **TR: Low priority, won't cause errors**

Robot.java
45-46, 48, 51-52 - variables never used  **TR: Low priority, won't cause errors**
31, 36, 65, 69 - don't initialize a class more than once, we don't have 2 gyros or 2 drive trains **: TR - these lines define the variables as class variables, but do not create the class. Not a problem.** Manoli: Just an idea, I was talking with Paul and he was saying it would be good to just input the existing object when you construct the class and use the "this" function so it doesn't cause any potential problems
NOTE: could not check 81-110, had no idea what this does (please comment)
107, 111-114 - unnecessary, please delete (stylistic mostly) **TR: Low priority, won't cause errors**
123-130 - there should be functions for toggling brake mode and setting ramp rate of talons **TR: don't know, MEDIUM PRIORITY** Manoli: This just increases readability in the code, and makes it easier to understand and fix. This isn't super high priority, it's just helpful to have
131-133 - both of these reset they gyro, delete the gyro one (stylistic mostly, but this should go as part of not initializing gyro again) **TR: Low priority, won't cause errors**
190 - un-comment this, we should have an option for shooting in teleop in case we don't in autonomous. REMEMBER - those few points do make a difference!!! **TR - won't all balls be gone in teleop?** Manoli: Not if we don't start on a side with the hopper, and since we are allowed to load them before regardless they'll be there. Even on the side with the hopper, there is a small chance we don't get there or something goes wrong and it can't reach that.

This is my feedback for the code. I'd love it if the programming mentors, Spencer, and Max could go through this too! Thanks guys!

Edit: Thanks for reviewing this, Tom! I put answers to some of your questions above.

**Comment by tremmers** [comment]
I’ll take a look

**Comment by manolipt** [comment]
Thanks Tom!

**Comment by tremmers** [comment]
I noted a couple things of concern, look for HIGH PRIORTY and MEDIUM PRIORITY in the issue, https://github.com/Team-Pronto-3070/2017_Master/issues/39, specifically,

Auto.java

line 99 - should be an else if statement TR: HIGH PRIORITY YES, even worse turnStarted is never set to true. Bad logic

line 99 - turnStarted needs to be set to true in this statement, otherwise program will not continue TR: HIGH PRIORITY

All instances of drive.turn - the speed should be set to Pronstants.AUTO_TURN_SPEED TR: HIGH PRIORITY – YES

line 173 - Why is this here? TR: HIGH PRIORITY ? won't this keep changing the initHeading every cycle?

Drive.java

164 - robot will only drive if you tell it to TR: won't it not drive if it's wrong? TEST IT!! HIGH PRIORITY 

Robot.java

123-130 - there should be functions for toggling brake mode and setting ramp rate of talons TR: don't know, MEDIUM PRIORITY

Who is going up for Friday? Should I join you? Seems like it might be helpfule.

**Comment by manolipt** [comment]
Hey guys, one more thing: make sure that you put the final code for this weekend's competition in a separate repo so it's easier to access and nothing gets edited without the programmers noticing. Again, thank you for reviewing this Tom, I put some answers to some of your questions/extra comments in the original issue above.

I will only be available today until 3:15 or so, after that I have to go. I will send out an email too but I will be at the autoshop within about 5 minutes of school ending, I know mentors can't make it that fast but if any team members can I want to have the maximum amount of time to review this code. Thanks for an awesome season you guys and I'll see you at the meeting! Go Pronto!
